### ISSUE TITLE
output is not generating letter by letter, instead all at once

### ISSUE THREAD

**Issue by ssrikanthreddy** [hinterdupfinger/obsidian-ollama#16]
The out put from the models is not generating/showing letter by letter, but instead, its taking time till the end of the API call, and showing all at once. How do i get it to show letter by letter like chat GPT or something?

**Comment by zlatent** [comment]
you're essentially asking for `streaming`. there is an open PR on this.

**Comment by ssrikanthreddy** [comment]
@zz2115 thanks, I'll look into it
